// src/apps/web/src/pages/LoginPage.jsx
import { useMemo, useState } from 'react';
import { login } from '../composables/useAuth.js';

export default function LoginPage() {
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [error, setError] = useState('');

    const canSubmit = useMemo(() => username.trim() && password, [password, username]);

    async function submit(e) {
        e.preventDefault();
        setError('');
        if (!canSubmit) return;

        setIsSubmitting(true);
        try {
            await login({ username: username.trim(), password });
        } catch (caught) {
            setError(caught?.message || String(caught));
        } finally {
            setIsSubmitting(false);
        }
    }

    return (
        <div className="auth-card">
            <div className="mb-6">
                <div className="text-xs tracking-wide text-text-muted">Admin sign in</div>
                <h1 className="text-3xl font-bold mt-2">登录</h1>
                <p className="text-sm text-text-muted mt-2">请输入管理员账号密码。</p>
            </div>

            <form className="space-y-4" onSubmit={submit}>
                <div>
                    <label className="form-label">用户名</label>
                    <input
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                        className="form-input"
                        type="text"
                        autoComplete="username"
                    />
                </div>

                <div>
                    <label className="form-label">密码</label>
                    <input
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        className="form-input"
                        type="password"
                        autoComplete="current-password"
                    />
                </div>

                {error ? (
                    <div className="rounded-xl border border-error/25 bg-error/10 p-4 text-error text-sm">
                        {error}
                    </div>
                ) : null}

                <button
                    className="btn btn-primary btn-full"
                    disabled={!canSubmit || isSubmitting}
                    type="submit"
                >
                    <i
                        className={
                            isSubmitting
                                ? 'fas fa-spinner fa-spin'
                                : 'fas fa-right-to-bracket'
                        }
                    ></i>
                    登录
                </button>
            </form>
        </div>
    );
}

// src/apps/web_console/src/pages/LoginPage.vue
<template>
    <div class="auth-page">
        <div class="auth-container">
            <div class="auth-card">
                <div class="auth-header">
                    <div class="auth-logo">
                        <img src="/logo.png" alt="Arkanis" />
                        <span>Arkanis</span>
                    </div>
                    <h1 class="auth-title">登录</h1>
                    <p class="auth-subtitle">进入 SaaS 控制台</p>
                </div>

                <form @submit.prevent="onSubmit">
                    <div class="form-group">
                        <label class="form-label" for="email">邮箱</label>
                        <input id="email" v-model="email" class="form-input" type="email" autocomplete="email" required />
                    </div>

                    <div class="form-group">
                        <label class="form-label" for="password">密码</label>
                        <input
                            id="password"
                            v-model="password"
                            class="form-input"
                            type="password"
                            autocomplete="current-password"
                            required
                        />
                        <p v-if="error" class="form-error">{{ error }}</p>
                    </div>

                    <button class="btn btn-primary btn-full" type="submit" :disabled="submitting">
                        {{ submitting ? '登录中...' : '登录' }}
                    </button>
                </form>

                <div class="auth-footer">
                    <p>
                        还没有账号？
                        <RouterLink class="link" to="/register">注册</RouterLink>
                    </p>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import { RouterLink, useRouter } from 'vue-router';
import { useAuthStore } from '../stores/authStore.js';

const auth = useAuthStore();
const router = useRouter();

const email = ref('');
const password = ref('');
const error = ref('');
const submitting = ref(false);

async function onSubmit() {
    error.value = '';
    submitting.value = true;
    try {
        await auth.login({ email: email.value.trim(), password: password.value });
        await router.push('/app');
    } catch (e) {
        error.value = e?.message || '登录失败';
    } finally {
        submitting.value = false;
    }
}
</script>
