// src/apps/web_console/src/components/IndicatorViewsCard.vue
<template>
    <div v-if="views" class="iv-card">
        <div class="iv-header">
            <div class="iv-title">
                <span class="iv-title-text">{{ title }}</span>
            </div>
            <span class="iv-subtitle">AI 观点</span>
        </div>

        <div class="iv-body">
            <div v-for="item in items" :key="item.key" class="iv-row">
                <div class="iv-row-top">
                    <span class="iv-left">{{ item.name }}</span>
                    <span :class="item.badgeClass">{{ item.right }}</span>
                </div>
                <div v-if="item.note" class="iv-note">{{ item.note }}</div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({
    views: { type: Object, default: null },
    title: { type: String, default: '指标观点' },
});

function normalizeBias(value) {
    const v = String(value || '').trim().toLowerCase();
    if (['bullish', 'long', 'buy', '看多', '偏多', '多', '多头'].includes(v)) return 'bullish';
    if (['bearish', 'short', 'sell', '看空', '偏空', '空', '空头'].includes(v)) return 'bearish';
    if (['neutral', 'none', 'wait', 'hold', '中性', '观望'].includes(v)) return 'neutral';
    return v || 'neutral';
}

function normalizeStrengthLevel(value) {
    const v = String(value || '').trim().toLowerCase();
    if (['above_average', 'above', 'strong', 'high', '高于平均', '偏强', '强'].includes(v)) return 'above_average';
    if (['below_average', 'below', 'weak', 'low', '低于平均', '偏弱', '弱'].includes(v)) return 'below_average';
    if (['average', 'mid', 'normal', '中等', '平均', '一般'].includes(v)) return 'average';
    return v || 'average';
}

function biasLabel(bias) {
    const b = normalizeBias(bias);
    if (b === 'bullish') return '偏多';
    if (b === 'bearish') return '偏空';
    if (b === 'neutral') return '中性';
    return b;
}

function strengthLabel(level) {
    const l = normalizeStrengthLevel(level);
    if (l === 'above_average') return '高于平均';
    if (l === 'below_average') return '低于平均';
    if (l === 'average') return '平均';
    return l;
}

function badgeClassByBias(bias) {
    const b = normalizeBias(bias);
    if (b === 'bullish') return 'iv-badge iv-badge--bullish';
    if (b === 'bearish') return 'iv-badge iv-badge--bearish';
    return 'iv-badge iv-badge--neutral';
}

const items = computed(() => {
    const v = props.views || {};

    const bollBias = normalizeBias(v?.bollinger?.bias);
    const macdBias = normalizeBias(v?.macd?.bias);
    const adxLevel = normalizeStrengthLevel(v?.trend_strength?.level);
    const adxBias = normalizeBias(v?.trend_strength?.bias);

    const score =
        (bollBias === 'bullish' ? 1 : bollBias === 'bearish' ? -1 : 0) +
        (macdBias === 'bullish' ? 1 : macdBias === 'bearish' ? -1 : 0) +
        (adxBias === 'bullish' ? 1 : adxBias === 'bearish' ? -1 : 0);

    const overallBias = score >= 2 ? 'bullish' : score <= -2 ? 'bearish' : 'neutral';

    return [
        { key: 'macd', name: 'MACD', right: biasLabel(macdBias), badgeClass: badgeClassByBias(macdBias), note: v?.macd?.note || '' },
        { key: 'boll', name: '布林带', right: biasLabel(bollBias), badgeClass: badgeClassByBias(bollBias), note: v?.bollinger?.note || '' },
        {
            key: 'trend',
            name: '趋势强度',
            right: `${strengthLabel(adxLevel)} · ${biasLabel(adxBias)}`,
            badgeClass: 'iv-badge iv-badge--purple',
            note: v?.trend_strength?.note || '',
        },
        { key: 'overall', name: '综合倾向', right: biasLabel(overallBias), badgeClass: badgeClassByBias(overallBias), note: '' },
    ];
});
</script>

<style scoped>
.iv-card {
    background: rgba(0, 0, 0, 0.45);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: var(--radius-2xl);
    overflow: hidden;
}

.iv-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem 1.25rem;
    border-bottom: 1px solid rgba(255, 255, 255, 0.06);
}

.iv-title-text {
    font-size: var(--font-size-sm);
    font-weight: 700;
    color: rgba(255, 255, 255, 0.8);
}

.iv-subtitle {
    font-size: 0.75rem;
    color: rgba(255, 255, 255, 0.25);
}

.iv-body {
    display: flex;
    flex-direction: column;
}

.iv-row {
    padding: 1rem 1.25rem;
    border-bottom: 1px solid rgba(255, 255, 255, 0.06);
}

.iv-row:last-child {
    border-bottom: none;
}

.iv-row-top {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
}

.iv-left {
    font-size: 0.95rem;
    color: rgba(255, 255, 255, 0.72);
    letter-spacing: 0.2px;
}

.iv-note {
    margin-top: 0.5rem;
    font-size: 0.8rem;
    color: rgba(255, 255, 255, 0.35);
    line-height: 1.4;
}

.iv-badge {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: 64px;
    padding: 0.35rem 0.85rem;
    border-radius: 9999px;
    font-size: 0.78rem;
    font-weight: 700;
    letter-spacing: 0.3px;
    border: 1px solid rgba(255, 255, 255, 0.08);
    background: rgba(255, 255, 255, 0.06);
    color: rgba(255, 255, 255, 0.78);
}

.iv-badge--bullish {
    background: rgba(52, 199, 89, 0.14);
    border-color: rgba(52, 199, 89, 0.22);
    color: rgba(120, 255, 170, 0.9);
}

.iv-badge--bearish {
    background: rgba(255, 59, 48, 0.14);
    border-color: rgba(255, 59, 48, 0.22);
    color: rgba(255, 140, 135, 0.92);
}

.iv-badge--neutral {
    background: rgba(90, 200, 250, 0.12);
    border-color: rgba(90, 200, 250, 0.18);
    color: rgba(150, 225, 255, 0.9);
}

.iv-badge--purple {
    background: rgba(175, 82, 222, 0.14);
    border-color: rgba(175, 82, 222, 0.22);
    color: rgba(224, 174, 255, 0.92);
}
</style>

// src/apps/web/src/components/IndicatorViewsCard.jsx
import { useMemo } from 'react';

function normalizeBias(value) {
    const v = String(value || '').trim().toLowerCase();
    if (['bullish', 'long', 'buy', '看多', '偏多', '多', '多头'].includes(v)) return 'bullish';
    if (['bearish', 'short', 'sell', '看空', '偏空', '空', '空头'].includes(v)) return 'bearish';
    if (['neutral', 'none', 'wait', 'hold', '中性', '观望'].includes(v)) return 'neutral';
    return v || 'neutral';
}

function normalizeStrengthLevel(value) {
    const v = String(value || '').trim().toLowerCase();
    if (['above_average', 'above', 'strong', 'high', '高于平均', '偏强', '强'].includes(v)) return 'above_average';
    if (['below_average', 'below', 'weak', 'low', '低于平均', '偏弱', '弱'].includes(v)) return 'below_average';
    if (['average', 'mid', 'normal', '中等', '平均', '一般'].includes(v)) return 'average';
    return v || 'average';
}

function biasLabel(bias) {
    const b = normalizeBias(bias);
    if (b === 'bullish') return '偏多';
    if (b === 'bearish') return '偏空';
    if (b === 'neutral') return '中性';
    return b;
}

function strengthLabel(level) {
    const l = normalizeStrengthLevel(level);
    if (l === 'above_average') return '高于平均';
    if (l === 'below_average') return '低于平均';
    if (l === 'average') return '平均';
    return l;
}

function badgeClassByBias(bias) {
    const b = normalizeBias(bias);
    if (b === 'bullish') return 'iv-badge iv-badge--bullish';
    if (b === 'bearish') return 'iv-badge iv-badge--bearish';
    return 'iv-badge iv-badge--neutral';
}

export default function IndicatorViewsCard({ views = null, title = '指标观点' }) {
    const items = useMemo(() => {
        const v = views || {};

        const bollBias = normalizeBias(v?.bollinger?.bias);
        const macdBias = normalizeBias(v?.macd?.bias);
        const adxLevel = normalizeStrengthLevel(v?.trend_strength?.level);
        const adxBias = normalizeBias(v?.trend_strength?.bias);

        const score =
            (bollBias === 'bullish' ? 1 : bollBias === 'bearish' ? -1 : 0) +
            (macdBias === 'bullish' ? 1 : macdBias === 'bearish' ? -1 : 0) +
            (adxBias === 'bullish' ? 1 : adxBias === 'bearish' ? -1 : 0);

        const overallBias = score >= 2 ? 'bullish' : score <= -2 ? 'bearish' : 'neutral';

        return [
            {
                key: 'macd',
                name: 'MACD',
                right: biasLabel(macdBias),
                badgeClass: badgeClassByBias(macdBias),
                note: v?.macd?.note || '',
            },
            {
                key: 'boll',
                name: '布林带',
                right: biasLabel(bollBias),
                badgeClass: badgeClassByBias(bollBias),
                note: v?.bollinger?.note || '',
            },
            {
                key: 'trend',
                name: '趋势强度',
                right: `${strengthLabel(adxLevel)} · ${biasLabel(adxBias)}`,
                badgeClass: 'iv-badge iv-badge--purple',
                note: v?.trend_strength?.note || '',
            },
            {
                key: 'overall',
                name: '综合倾向',
                right: biasLabel(overallBias),
                badgeClass: badgeClassByBias(overallBias),
                note: '',
            },
        ];
    }, [views]);

    if (!views) return null;

    return (
        <div
            className="indicator-views-card glass-card iv-card overflow-hidden"
            style={{
                '--glass-bg': 'rgba(5, 6, 12, 0.72)',
                '--glass-border': 'rgba(255, 255, 255, 0.08)',
            }}
        >
            <div className="px-6 pt-5 pb-4 border-b border-white/5">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <i className="fas fa-chart-line text-white/55 text-sm"></i>
                        <span className="text-label text-white/80">{title}</span>
                    </div>
                    <span className="text-xs text-white/25">AI 观点</span>
                </div>
            </div>

            <div className="divide-y divide-white/5">
                {items.map((item) => (
                    <div key={item.key} className="px-6 py-4 iv-row">
                        <div className="flex items-center justify-between gap-4">
                            <span className="text-sm text-white/70 tracking-wide">
                                {item.name}
                            </span>
                            <span className={item.badgeClass}>{item.right}</span>
                        </div>
                        {item.note ? (
                            <div className="mt-2 text-xs text-white/35 leading-relaxed line-clamp-2">
                                {item.note}
                            </div>
                        ) : null}
                    </div>
                ))}
            </div>
        </div>
    );
}
